include ~/.config/omarchy/current/theme/kitty.conf

# Font
font_family JetBrainsMono Nerd Font
bold_italic_font auto
font_size        12.0

# Window
window_padding_width 14
window_padding_height 14
hide_window_decorations yes
show_window_resize_notification no
confirm_os_window_close 0

# Keybindings
map F11 toggle_fullscreen
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard

# Allow remote access
single_instance yes
allow_remote_control yes

# Aesthetics
cursor_shape block
enable_audio_bell no
background_opacity 0.95

# Clipboard & Selection
copy_on_select clipboard
strip_trailing_spaces smart

# Minimal Tab bar styling 
tab_bar_edge                top
tab_bar_align               center
tab_bar_style               separator
tab_separator               "  "
tab_bar_min_tabs            2
tab_bar_margin_width        2.0
tab_bar_margin_height       2.0 0.0
tab_bar_background          none
tab_title_template          " {title} "
active_tab_font_style       bold
inactive_tab_font_style     normal
active_tab_foreground       #a4a4a4
active_tab_background       #121212
inactive_tab_foreground     #605d5b
inactive_tab_background     #121212

# cursor trail
cursor_trail 3

include bindings.conf

