include ~/.config/omarchy/current/theme/kitty.conf

# Font
font_family JetBrainsMono Nerd Font
bold_italic_font auto
font_size        14.0

# Window
window_padding_width 14
window_padding_height 14
hide_window_decorations yes
show_window_resize_notification no
confirm_os_window_close 1

# Keybindings
map F11 toggle_fullscreen
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard

# Allow remote access
single_instance yes
allow_remote_control yes

# Aesthetics
cursor_shape block
enable_audio_bell no
#background_opacity 0.95

# Clipboard & Selection
copy_on_select clipboard
strip_trailing_spaces smart
select_by_word_characters @-./_~?&=%+#

# Minimal Tab bar styling
tab_bar_edge                top
tab_bar_align               center
tab_bar_style               separator
tab_separator               "  "
tab_bar_min_tabs            2
tab_bar_margin_width        2.0
tab_bar_margin_height       2.0 0.0
tab_title_template          " {title} "
active_tab_font_style       bold
inactive_tab_font_style     normal
include ~/.config/kitty/omarchy-tabbar.conf

# cursor trail
cursor_trail 5
cursor_blink true

include bindings.conf
