# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
cwd = { fg = "#8ec07c" }

hovered         = { reversed = true }
preview_hovered = { underline = true }

find_keyword  = { fg = "#fabd2f", bold = true, italic = true, underline = true }
find_position = { fg = "#d3869b", bg = "reset", bold = true, italic = true }

marker_copied   = { fg = "#b8bb26", bg = "#b8bb26" }
marker_cut      = { fg = "#fb4934", bg = "#fb4934" }
marker_marked   = { fg = "#83a598", bg = "#83a598" }
marker_selected = { fg = "#fabd2f", bg = "#fabd2f" }

count_copied   = { fg = "#32302f", bg = "#b8bb26" }
count_cut      = { fg = "#32302f", bg = "#fb4934" }
count_selected = { fg = "#32302f", bg = "#fabd2f" }

border_symbol = "│"
border_style  = { fg = "#706e6b" }

# : }}}


# : Tabs {{{

[tabs]
active   = { fg = "#32302f", bg = "#83a598", bold = true }
inactive = { fg = "#83a598", bg = "#7b6d60" }

# : }}}


# : Mode {{{

[mode]

normal_main = { fg = "#32302f", bg = "#83a598", bold = true }
normal_alt  = { fg = "#83a598", bg = "#7b6d60" }

select_main = { fg = "#32302f", bg = "#8ec07c", bold = true }
select_alt  = { fg = "#8ec07c", bg = "#7b6d60" }

unset_main = { fg = "#32302f", bg = "#d3869b", bold = true }
unset_alt  = { fg = "#d3869b", bg = "#7b6d60" }

# : }}}


# : Status bar {{{

[status]
perm_sep   = { fg = "#706e6b" }
perm_type  = { fg = "#83a598" }
perm_read  = { fg = "#fabd2f" }
perm_write = { fg = "#fb4934" }
perm_exec  = { fg = "#b8bb26" }

progress_label  = { fg = "#f0e4c5", bold = true }
progress_normal = { fg = "#83a598", bg = "#7b6d60" }
progress_error  = { fg = "#fb4934", bg = "#7b6d60" }

# : }}}


# : Pick {{{

[pick]
border   = { fg = "#83a598" }
active   = { fg = "#d3869b", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#83a598" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border = { fg = "#83a598" }

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#83a598" }
title   = {}
hovered = { fg = "#d3869b", underline = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#7b6d60" }
cand            = { fg = "#8ec07c" }
rest            = { fg = "#a89984" }
desc            = { fg = "#d3869b" }
separator       = "  "
separator_style = { fg = "#706e6b" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#8ec07c" }
run     = { fg = "#d3869b" }
hovered = { reversed = true, bold = true }
footer  = { fg = "#7b6d60", bg = "#ebdbb2" }

# : }}}


# : Notify {{{

[notify]
title_info  = { fg = "#b8bb26" }
title_warn  = { fg = "#fabd2f" }
title_error = { fg = "#fb4934" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#8ec07c" },

	# Media
	{ mime = "{audio,video}/*", fg = "#fabd2f" },

	# Archives
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#d3869b" },

	# Documents
	{ mime = "application/{pdf,doc,rtf}", fg = "#b8bb26" },

	# Fallback
	{ url = "*", fg = "#ebdbb2" },
	{ url = "*/", fg = "#83a598" },

	{ name = "*", fg = "#ebdbb2" },
	{ name = "*/", fg = "#83a598" }
]

# : }}}
