# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale
# You must relaunch Hyprland after changing any envs (use Super+Esc, then Relaunch)

# Optimized for retina-class 2x displays, like 13" 2.8K, 27" 5K, 32" 6K.
#env = GDK_SCALE,2
#monitor=,preferred,auto,auto

# Good compromise for 27" or 32" 4K monitors (but fractional!)
env = GDK_SCALE,1.666667

# Monitor configuration for clamshell mode  
monitor = eDP-1, 1920x1200@60.00100, auto, 1       # Internal display (ThinkPad T14s Gen 3)

# Home office setup
monitor = desc:BenQ RD320UA, 3840x2160@60, 1920x0, 1.666667     # BenQ RD320UA 4K monitor with 1.666667x scaling (matches by description)

# Work office setup  
monitor = DP-1, 2560x1440@59.95100, 1920x0, 1      # Dell P3223DE monitor

# Example for Framework 13 w/ 6K XDR Apple display
# monitor = DP-5, 6016x3384@60, auto, 2
# monitor = eDP-1, 2880x1920@120, auto, 2
