map ctrl+v>c new_tab
map ctrl+v>x close_tab
map ctrl+v>n next_tab
map ctrl+v>p previous_tab
map ctrl+v>, set_tab_title
map ctrl+v>. move_tab_forward
map ctrl+v>< move_tab_backward

map ctrl+v>1 goto_tab 1
map ctrl+v>2 goto_tab 2
map ctrl+v>3 goto_tab 3
map ctrl+v>4 goto_tab 4
map ctrl+v>5 goto_tab 5
map ctrl+v>6 goto_tab 6
map ctrl+v>7 goto_tab 7
map ctrl+v>8 goto_tab 8
map ctrl+v>9 goto_tab 9

map ctrl+v>% launch --location=vsplit --cwd=current
map ctrl+v>" launch --location=hsplit --cwd=current
map ctrl+v>z toggle_layout stack

map ctrl+v>h neighboring_window left
map ctrl+v>j neighboring_window down
map ctrl+v>k neighboring_window up
map ctrl+v>l neighboring_window right

map ctrl+v>w close_window
map ctrl+v>d quit
map ctrl+v>shift+r load_config_file

map --new-mode resize ctrl+v>r
map --mode resize h resize_window narrower
map --mode resize j resize_window shorter
map --mode resize k resize_window taller
map --mode resize l resize_window wider
map --mode resize shift+h resize_window narrower 5
map --mode resize shift+j resize_window shorter 5
map --mode resize shift+k resize_window taller 5
map --mode resize shift+l resize_window wider 5
map --mode resize = resize_window reset
map --mode resize esc pop_keyboard_mode
map --mode resize enter pop_keyboard_mode
map --mode resize q pop_keyboard_mode

map ctrl+v>[ launch --stdin-source=@screen_scrollback --type=overlay nvim -c "set nolist nonumber norelativenumber" -c "autocmd TermOpen * normal G" -

map ctrl+v>s combine : new_tab : set_tab_title main : new_tab : set_tab_title AI : new_tab : set_tab_title temp : new_tab : set_tab_title temp2 : goto_tab 1
