term xterm-256color

font_family postscript_name=MesloLGSNF-Regular
bold_font auto
italic_font auto
bold_italic_font auto

hide_window_decorations titlebar-and-corners
confirm_os_window_close 0
background_opacity 1.0

foreground #cdd6f4
background #1e1e2e
selection_foreground #1e1e2e
selection_background #f5c2e7
cursor #f5c2e7
cursor_text_color #1e1e2e

color0 #45475a
color1 #f38ba8
color2 #a6e3a1
color3 #f9e2af
color4 #89b4fa
color5 #f5c2e7
color6 #94e2d5
color7 #bac2de
color8 #585b70
color9 #f38ba8
color10 #a6e3a1
color11 #f9e2af
color12 #89b4fa
color13 #f5c2e7
color14 #94e2d5
color15 #a6adc8
color16 #fab387
color17 #f5c2e7

tab_bar_edge top
tab_bar_align center
tab_bar_style separator
tab_separator "  "
tab_bar_min_tabs 2
tab_bar_margin_width 2.0
tab_bar_margin_height 2.0 0.0
tab_bar_background #1e1e2e
tab_title_template " {title} "
active_tab_font_style bold
inactive_tab_font_style normal
active_tab_foreground #d4a5ff
active_tab_background #1e1e2e
inactive_tab_foreground #8b9aff
inactive_tab_background #1e1e2e

map F11 toggle_fullscreen
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard
map shift+enter send_text all \x1b\r

allow_remote_control yes

cursor_shape block
cursor_trail 5
cursor_blink_interval -1
cursor_stop_blinking_after 0
enable_audio_bell no

copy_on_select clipboard
strip_trailing_spaces smart
select_by_word_characters @-./_~?&=%+#

include bindings.conf
